"""user is active

Revision ID: 80d3d2bff9f1
Revises: 67bc6616185d
Create Date: 2025-03-02 21:54:19.416392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80d3d2bff9f1'
down_revision: Union[str, None] = '67bc6616185d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_column('api_keys', 'hashed_key')
    # ### end Alembic commands ###
